version: 0.2
env:
  secrets-manager:
    TOKEN: veryimportantProd1
phases:
  build:
    commands:
      - echo "Running Maven verify..."
      - mvn verify
      - echo "Running SonarCloud analysis with full error details..."
      - mvn sonar:sonar -e -X -Dsonar.projectKey=javaprojectnaz -Dsonar.organization=DevSecOpsNaz -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOKEN
