version: 0.2
env:
  secrets-manager:
    TOKEN: veryimportantProd1
phases:
  build:
    commands:
      - echo "Starting Maven build..."
      - mvn verify
      - echo "Starting SonarCloud analysis..."
      - mvn sonar:sonar -Dsonar.projectKey=javaprojectnaz -Dsonar.organization=DevSecOpsNaz -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOKEN
