version: 0.2
env:
    secrets-manager:
      TOKEN: veryimportantProd1
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=Java Project -Dsonar.organization=DevSecOps Naz -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN
