version: 0.2
env:
  secrets-manager:
    LOGIN: veryimportantProd1:sonartoken
    HOST: veryimportantProd1:HOST
    Organization: veryimportantProd1:Organization
    Project: veryimportantProd1:Project
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey="$Project" -Dsonar.organization="$Organization" -Dsonar.host.url="$HOST" -Dsonar.login="$LOGIN"
