version: 0.2
env:
  secrets-manager:
    LOGIN: veryimportantProd1:sonartoken
    HOST: veryimportantProd1:HOST
    Organization: veryimportantProd1:Organization
    Project: veryimportantProd1:Project
phases:
  install:
    runtime-versions:
      java: corretto11  # Updated from openjdk8
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - apt-get update
      - apt-get install -y jq wget unzip
      # Maven installation
      - cd /tmp
      - wget https://archive.apache.org/dist/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
      - tar xzf apache-maven-3.8.6-bin.tar.gz
      - mv apache-maven-3.8.6 /opt/maven
      - export PATH=/opt/maven/bin:$PATH
      - export M2_HOME=/opt/maven
      # SonarQube Scanner installation
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
      - unzip sonar-scanner-cli-4.8.0.2856-linux.zip
      - mv sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner
      - export PATH=/opt/sonar-scanner/bin:$PATH
      - cd $CODEBUILD_SRC_DIR
  build:
    commands:
      - echo "Running Maven tests..."
      - mvn clean test
      - echo "Running SonarQube analysis..."
      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - echo "Waiting for quality gate result..."
      - sleep 10
      - curl -s "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project" > result.json
      - cat result.json
      - echo "Checking quality gate status..."
      - QUALITY_GATE_STATUS=$(jq -r '.projectStatus.status' result.json)
      - echo "Quality Gate Status: $QUALITY_GATE_STATUS"
      - |
        if [ "$QUALITY_GATE_STATUS" = "ERROR" ]; then
          echo "Quality gate failed!"
          exit 1
        else
          echo "Quality gate passed!"
        fi
